routes/web.php
<?php
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PracticeController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\FieldsOfPracticeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register' => false
]);

Route::resource('practices', PracticeController::class)->middleware([
    'auth'
]);
Route::resource('employees', EmployeeController::class)->middleware([
    'auth'
]);
Route::resource('fields-of-practice', FieldsOfPracticeController::class)->middleware([
    'auth'
]);

Route::delete('delete-practice', [PracticeController::class, 'destroy'])->name("delete-practice");

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
	protected $fillable = ['first_name', 'last_name', 'practice_id', 'email', 'phone'];

    public function practice()
    {
        return $this->belongsTo('App\Practice')->withDefault();
    }

    public function getFullNameAttribute()
    {
    	return $this->first_name . ' ' . $this->last_name;
    }
}

app/Practice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\UploadedFile;

class Practice extends Model
{
    protected $fillable = ['name', 'email', 'logo', 'url'];

    public function employees()
    {
        return $this->hasMany('App\Employee');
    }

    public function fieldsOfPractice()
    {
        return $this->belongsToMany('App\FieldsOfPractice');
    }

    public function getLogoAttribute($value)
    {
        // The actual path from which the logo can be accessed publicly can vary (based on config)
        $fullUrl = preg_match('{https?\:\/\/}', $value);

        if($fullUrl) return $value;
        if(empty($value)){
            return false;
        }
        return Storage::url($value);
    }

    public function setLogoAttribute($value)
    {
        if(NULL === $value) return NULL;

        if(is_string($value)) $this->attributes['logo'] = $value;

        if($value instanceof UploadedFile) {
            $logo = $value->store('logos', ['disk' => 'public']);
            $this->attributes['logo'] = $logo;
        }
    }

    public function getUrlAttribute($value)
    {
        if(NULL === $value) return NULL;

        // Prepend 'http://' to the website if it's not set already (http or https). This is to make sure the website URL is treated as an external link when rendered (i.e. avoid having a link like this: https://this-app.com/practice-website.com, but instead: http://practice-website.com)
        return preg_match('^https?\:\/\/^', $value) ? $value : 'http://' . $value;
    }
}

app/Http/Controllers/API/PracticeController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Practice;

class PracticeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return Practice::paginate(10);
    }
}

app/Http/Controllers/PracticeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Http\Requests\Practice\StorePracticeRequest;
use App\Http\Requests\Practice\UpdatePracticeRequest;
use App\Practice;
use App\FieldsOfPractice;
use App\Rules\MinImageWidth;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PracticeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $response = Practice::query();
        if($request->input('name')){
            $response->where("name", 'like', "%".$request->input('name')."%");
        }   

        $practices = $response->paginate($this->pageLimit);
        return view('practices.index', compact('practices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $fieldsOfPractice = FieldsOfPractice::all();
        return view('practices.create', compact('fieldsOfPractice'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Practice\StorePracticeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePracticeRequest $request)
    {
        try {
            $practice = Practice::create($request->all());
            $practice->fieldsOfPractice()->sync($request->input('fields_of_practice'));
        } catch (Exception $e) {
            return back()->withError(__('Failure saving a new practice! Please try again.'));
        }
        return redirect()->route('practices.show', $practice)->withSuccess(__('Success!'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Practice $practice)
    {
        $fieldsOfPractice = FieldsOfPractice::all();
        return view('practices.show', compact('practice', 'fieldsOfPractice'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Practice $practice)
    {
        $fieldsOfPractice = FieldsOfPractice::all();
        return view('practices.edit', compact('practice', 'fieldsOfPractice'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Practice\UpdatePracticeRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePracticeRequest $request, Practice $practice)
    {
        try {
            $practice->update($request->all());
            $practice->fieldsOfPractice()->sync($request->input('fields_of_practice'));
        } catch (Exception $e) {
            return back()->withError(__('Failure updating! Please try again.')); 
        }
        return redirect()->route('practices.show', $practice)->withSuccess(__('Success!'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Practice $practice)
    {
        try {
            $practice->delete();
        } catch (Exception $e) {
            return back()->withError(__('Failure deleting! Please check if there are employees or fields of practice still connected to this practice and try again.'));
        }
        return redirect()->route('practices.index')->withSuccess(__('Practice deleted successfully!'));
    }
}

resources/views/practices/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(Session::has('success'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create Practice') }}</div>
                
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{ route('practices.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}"  autocomplete="current-email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="logo" class="col-md-4 col-form-label text-md-right">{{ __('Logo') }}</label>

                            <div class="col-md-6">
                                <div class="custom-file">
                                    <input id="logo" type="file" class="custom-file-input form-control @error('logo') is-invalid @enderror" name="logo">
                                    <label for="logo" class="custom-file-label">{{ __('Logo') }}</label>

                                    @error('logo')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="url" class="col-md-4 col-form-label text-md-right">{{ __('URL') }}</label>

                            <div class="col-md-6">
                                <input id="url" type="text" class="form-control @error('url') is-invalid @enderror" name="url" value="{{ old('url') }}"s autocomplete="url">

                                @error('url')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">

                            <label for="fields-of-practice" class="col-md-4 col-form-label text-md-right">{{ __('Fields Of Practice') }}</label>
                            
                            <div class="col-md-6">
                                <select class="form-control @error('fields_of_practice') is-invalid @enderror" multiple="multiple" name="fields_of_practice[]" id="fields-of-practice" size="6">
                                    @foreach($fieldsOfPractice as $field)
                                        <option value="{{ $field->id }}">{{ $field->name }}</option>
                                    @endforeach
                                </select>

                                @error('fields_of_practice')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/practices/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(Session::has('success'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Update Practice') }}</div>
                <div class="card-body">
                    <form method="POST" enctype="multipart/form-data" action="{{ route('practices.update', $practice) }}">
                        @csrf
                        @method('PATCH')

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $practice->name }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $practice->email }}" autocomplete="current-email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="logo" class="col-md-4 col-form-label text-md-right">{{ __('Logo') }}</label>

                            <div class="col-md-6">
                                <div class="custom-file">
                                    <input id="logo" type="file" class="custom-file-input form-control @error('logo') is-invalid @enderror" name="logo">
                                    <label for="logo" class="custom-file-label">{{ __('Logo') }}</label>

                                    @error('logo')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="url" class="col-md-4 col-form-label text-md-right">{{ __('URL') }}</label>

                            <div class="col-md-6">
                                <input id="url" type="text" class="form-control @error('url') is-invalid @enderror" name="url" value="{{ $practice->url }}"s autocomplete="url">

                                @error('url')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="fields-of-practice" class="col-md-4 col-form-label text-md-right">{{ __('Fields Of Practice') }}</label>

                            <div class="col-md-6">
                                @foreach($fieldsOfPractice as $field)
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="field-of-practice-{{ $field->id }}" name="fields_of_practice[]" @if($practice->fieldsOfPractice->contains($field)) checked @endif value="{{ $field->id }}">
                                        <label for="field-of-practice-{{ $field->id }}"> {{ $field->name }}</label>
                                    </div>
                                @endforeach

                                @error('fields_of_practice')
                                    <span class="invalid-feedback d-block" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>

                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/practices/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="col-md-12 form-group">
        <form method="GET">
            <div class="row form-group">
                <div class="col-md-6">
                    <input type="text" placeholder="Name" class="form-control" name="name" value="<?=isset($_GET["name"]) ? $_GET["name"] : ''?>">
                </div>
            </div>
            <input type="submit" name="search" value="Search" class="btn btn-primary">
            <a href="{{ route('practices.create') }}" class="btn btn-success float-right" role="button" aria-pressed="true">{{ __('Create Practice') }}</a>
        </form>
    </div>

	@if(Session::has('success'))
		<div class="row mb-4 justify-content-center">
			<div class="col-md-12">
	            <div class="alert alert-success" role="alert">
	                {{ Session::get('success') }}
	            </div>
	        </div>
	    </div>
    @elseif(Session::has('error'))
	    <div class="row mb-4 justify-content-center">
			<div class="col-md-12">
	            <div class="alert alert-danger" role="alert">
	                {{ Session::get('error') }}
	            </div>
	        </div>
	    </div>
	@endif

    <div class="row justify-content-left">
        <div class="col-md-12">
            @if('practices')
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Logo</th>
                            <th scope="col">URL</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($practices as $practice)
                            <tr>
                                <td><a href="{{ route('practices.show', $practice) }}">{{ $practice->name }}</a></td>
                                <td>@if($practice->email){{ $practice->email }}@else-@endif</td>
                                <td>@if($practice->logo) <a target="_blank" href="{{ $practice->logo }}">{{ $practice->logo }}</a>@else-@endif</td>
                                <td>@if($practice->url)<a target="_blank" href="{{ $practice->url }}">{{ $practice->url }}</a>@else-@endif</td>
                                <td>
                                    <a class="btn btn-sm btn-primary float-left" href="{{ route('practices.edit', $practice) }}">Edit</a>
                                    <form id="delete-practice-form" action="{{ route('practices.destroy', $practice) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-sm btn-danger" value="Delete">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $practices->links() }}
            @else
            	<p class="alert alert-warning">No practices available. Click <a href="{{ route('practices.create') }}">here</a> to create a new practice.</p>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/practices/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if(Session::has('success'))
        <div class="row mb-4 justify-content-center">
            <div class="col-md-12">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row mb-4 justify-content-center">
            <div class="col-md-12">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif

    @if('practice')
     <div class="row md-4 justify-content-left">
        <div class="col-md-12">
            <h2>{{ $practice->name }}</h2>
            @if($practice->logo)<img width="100" alt="{{ $practice->name }}" src="{{ $practice->logo}}">@endif

            <hr>
            <p>Name: {{ $practice->name }}</p>
            <p>Email: @if($practice->email)<a href="mailto:{{ $practice->email }}">{{ $practice->email }}</a>@else-@endif</p>
            <p>Logo: @if($practice->logo)<a target="_blank" href="{{ $practice->logo }}">{{ $practice->logo }}</a>@else-@endif</p>
            <p>Website: @if($practice->url)<a href="{{ $practice->url }}">{{ $practice->url }}</a>@else-@endif</p>
        </div>
    </div>
    <div class="row md-4 justify-content-center">
        <div class="col-md-6">
        <h4>Employees</h4>
            <hr>
            @forelse($practice->employees as $employee)
                <li><a href="{{ route('employees.show', $employee) }}">{{ $employee->full_name }}</a></li>
            @empty
                <p class="alert alert-warning">No employees set.</p>
            @endforelse
        </div>
        <div class="col-md-6">
            <h4>Fields Of Practice</h4>
            <hr>
            <select class="form-control input-large" disabled="" multiple="multiple" name="fields_of_practice[]" id="fields-of-practice">
                @foreach($fieldsOfPractice as $field)
                    <option @if($practice->fieldsOfPractice->contains($field)) selected @endif value="{{ $field->id }}">{{ $field->name }}</option>
                @endforeach
            </select>
        </div>
    </div>
    @endif
</div>
@endsection