routes/web.php
<?php
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PracticeController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\FieldsOfPracticeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register' => false
]);

Route::resource('practices', PracticeController::class)->middleware([
    'auth'
]);
Route::resource('employees', EmployeeController::class)->middleware([
    'auth'
]);
Route::resource('fields-of-practice', FieldsOfPracticeController::class)->middleware([
    'auth'
]);

Route::delete('delete-practice', [PracticeController::class, 'destroy'])->name("delete-practice");

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/FieldsOfPractice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FieldsOfPractice extends Model
{
    protected $table = 'fields_of_practice';

    protected $fillable = ['name'];

    public function practices()
    {
        return $this->belongsToMany('App\Practice');
    }
}

app/Http/Controllers/FieldsOfPracticeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\FieldsOfPractice;
use App\Http\Requests\FieldsOfPractice\StoreFieldsOfPracticeRequest;
use App\Http\Requests\FieldsOfPractice\UpdateFieldsOfPracticeRequest;
use Exception;

class FieldsOfPracticeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $response = FieldsOfPractice::query();
        if($request->input('name')){
            $response->where("name", 'like', "%".$request->input('name')."%");
        }  

        $fieldsOfPractice = $response->paginate($this->pageLimit);
        return view('fields-of-practice.index', compact('fieldsOfPractice'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('fields-of-practice.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\FieldsOfPractice\StoreFieldsOfPracticeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreFieldsOfPracticeRequest $request)
    {
        try {
            $fieldsOfPractice = FieldsOfPractice::create($request->all());
        } catch (Exception $e) {
            return back()->withError(__('Failure creating field of practice! Please try again.')); 
        }
        return redirect()->route('fields-of-practice.show', $fieldsOfPractice)->withSuccess(__('Success!'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(FieldsOfPractice $fieldsOfPractice)
    {
        return view('fields-of-practice.show', compact('fieldsOfPractice'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(FieldsOfPractice $fieldsOfPractice)
    {
        return view('fields-of-practice.edit', compact('fieldsOfPractice'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\FieldsOfPractice\UpdateFieldsOfPracticeRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateFieldsOfPracticeRequest $request, FieldsOfPractice $fieldsOfPractice)
    {
        try {
            $fieldsOfPractice->update($request->all());
        } catch (Exception $e) {
            return back()->withError(__('Failure updating field of practice! Please try again.')); 
        }
        return redirect()->route('fields-of-practice.show', $fieldsOfPractice)->withSuccess(__('Success!'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(FieldsOfPractice $fieldsOfPractice)
    {
        try {
            $fieldsOfPractice->delete();
        } catch (Exception $e) {
            return back()->withError(__('Failure deleting field of practice! Please check if there are practices still connected to this field of practice and try again.')); 
        }
        return redirect()->route('fields-of-practice.index')->withSuccess(__('Field of practice deleted successfully!'));
    }
}

resources/views/fields-of-practice/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(Session::has('success'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create Field Of Practice') }}</div>
                
                <div class="card-body">
                    <form method="POST" action="{{ route('fields-of-practice.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/fields-of-practice/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(Session::has('success'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Update Practice') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('fields-of-practice.update', $fieldsOfPractice) }}">
                        @csrf
                        @method('PATCH')

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $fieldsOfPractice->name }}" required autocomplete="name" autofocus>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/fields-of-practice/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    <div class="col-md-12 form-group">
        <form method="GET">
            <div class="row form-group">
                <div class="col-md-6">
                    <input type="text" placeholder="Name" class="form-control" name="name" value="<?=isset($_GET["name"]) ? $_GET["name"] : ''?>">
                </div>
            </div>
            <input type="submit" name="search" value="Search" class="btn btn-primary">
            <a href="{{ route('fields-of-practice.create') }}" class="btn btn-success float-right" role="button" aria-pressed="true">{{ __('Create Field Of Practice') }}</a>
        </form>
    </div>

    @if(Session::has('success'))
        <div class="row mb-4 justify-content-center">
            <div class="col-md-12">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row mb-4 justify-content-center">
            <div class="col-md-12">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif

    <div class="row justify-content-left">
        <div class="col-md-12">
            @if('practices')
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($fieldsOfPractice as $field)
                            <tr>
                                <td><a href="{{ route('fields-of-practice.show', $field) }}">{{ $field->name }}</a></td>
                                 <td>
                                    <a class="btn btn-sm btn-primary float-left" href="{{ route('fields-of-practice.edit', $field) }}">Edit</a>
                                    <form id="delete-practice-form" action="{{ route('fields-of-practice.destroy', $field) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-sm btn-danger" value="Delete">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $fieldsOfPractice->links() }}
            @else
                <p class="alert alert-warning">No fields of practice available. Click <a href="{{ route('fields-of-practice.create') }}">here</a> to create a new field practice.</p>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/fields-of-practice/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(Session::has('success'))
        <div class="row mb-4 justify-content-center">
            <div class="col-md-12">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row mb-4 justify-content-center">
            <div class="col-md-12">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif
    
    @if('fieldsOfPractice')
     <div class="row md-4 justify-content-left">
        <div class="col-md-12">
            <h2>{{ $fieldsOfPractice->name }}</h2>
            <hr>
        </div>
    </div>
    <div class="row md-4 justify-content-center">
        <div class="col-md-12">
        <h4>Practices</h4>
            <hr>
            @forelse($fieldsOfPractice->practices as $practice)
                <li><a href="{{ route('practices.show', $practice) }}">{{ $practice->name }}</a></li>
            @empty
                <p class="alert alert-warning">{{ __('No practices set.')}}</p>
            @endforelse
        
        </div>
    </div>
    @endif

    <form id="delete-field-of-practice-form" action="{{ route('fields-of-practice.destroy', $fieldsOfPractice) }}" method="POST" style="display: none;">
        @csrf
        @method('DELETE')
    </form>
</div>
@endsection