routes/web.php
<?php
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PracticeController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\FieldsOfPracticeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register' => false
]);

Route::resource('practices', PracticeController::class)->middleware([
    'auth'
]);
Route::resource('employees', EmployeeController::class)->middleware([
    'auth'
]);
Route::resource('fields-of-practice', FieldsOfPracticeController::class)->middleware([
    'auth'
]);

Route::delete('delete-practice', [PracticeController::class, 'destroy'])->name("delete-practice");

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
	protected $fillable = ['first_name', 'last_name', 'practice_id', 'email', 'phone'];

    public function practice()
    {
        return $this->belongsTo('App\Practice')->withDefault();
    }

    public function getFullNameAttribute()
    {
    	return $this->first_name . ' ' . $this->last_name;
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Employee;
use App\Practice;
use App\Http\Requests\Employee\StoreEmployeeRequest;
use App\Http\Requests\Employee\UpdateEmployeeRequest;
use Exception;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $response = Employee::query();
        if($request->input('name')){
            $response->orWhere("first_name", 'like', "%".$request->input('name')."%");
            $response->orWhere("last_name", 'like', "%".$request->input('name')."%");
        }   

        $employees = $response->paginate($this->pageLimit);
        return view('employees.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $practices = Practice::all();
        return view('employees.create', compact('practices'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Request\Employee\StoreEmployeeRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEmployeeRequest $request)
    {
        try {
            $employee = Employee::create($request->all());
        } catch (Exception $e) {
            return back()->withError(__('Failure saving a new employee! Please try again.')); 
        }
        return redirect()->route('employees.show', $employee)->withSuccess(__('Success!'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return view('employees.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $practices = Practice::all();
        return view('employees.edit', compact('employee', 'practices'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Request\Employee\UpdateEmployeeRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEmployeeRequest $request, Employee $employee)
    {
        try {
            $employee->update($request->all());
        } catch (Exception $e) {
            return back()->withError(__('Failure updating employee! Please try again.')); 
        }
        return redirect()->route('employees.show', $employee)->withSuccess(__('Success!'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        try {
            $employee->delete();
        } catch (Exception $e) {
            return back()->withError(__('Failure deleting employee! Please try again.')); 
        }
        return redirect()->route('employees.index')->withSuccess(__('Employee deleted successfully!'));
    }
}

resources/views/employees/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(Session::has('success'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create Employee') }}</div>
                
                <div class="card-body">
                    <form method="POST" action="{{ route('employees.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="first-name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                            <div class="col-md-6">
                                <input id="first-name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') }}" required autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="last-name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                            <div class="col-md-6">
                                <input id="last-name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') }}" required autocomplete="last_name">

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="practice-id" class="col-md-4 col-form-label text-md-right">{{ __('Practice') }}</label>

                            <div class="col-md-6">

                                <select name="practice_id" id="practice-id" class="form-control @error('practice_id') is-invalid @enderror">
                                    <option value="">None</option>
                                    @foreach($practices as $practice)
                                        <option value="{{ $practice->id }}" @if($practice->id == old('practice_id')) selected @endif>{{ $practice->name }}</option>
                                    @endforeach
                                </select>

                                @error('practice_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="current-email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="phone" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ old('phone') }}" autocomplete="current-phone">

                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(Session::has('success'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Update Employee') }}</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('employees.update', $employee) }}">
                        @csrf
                        @method('PATCH')

                        <div class="form-group row">
                            <label for="first-name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                            <div class="col-md-6">
                                <input id="first-name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ $employee->first_name }}" required autocomplete="name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="last-name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                            <div class="col-md-6">
                                <input id="last-name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ $employee->last_name }}" required autocomplete="name" autofocus>

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('Email') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $employee->email }}" autocomplete="current-email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="practice-id" class="col-md-4 col-form-label text-md-right">{{ __('Practice') }}</label>

                            <div class="col-md-6">

                                <select name="practice_id" id="practice-id" class="form-control @error('practice_id') is-invalid @enderror">
                                    <option value="">None</option>
                                    @foreach($practices as $practice)
                                        <option value="{{ $practice->id }}" @if($employee->practice->id == $practice->id) selected @endif>{{ $practice->name }}</option>
                                    @endforeach
                                </select>

                                @error('practice_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone') }}</label>

                            <div class="col-md-6">
                                <input id="phone" type="phone" class="form-control @error('phone') is-invalid @enderror" name="phone" value="{{ $employee->phone }}" autocomplete="current-phone">

                                @error('phone')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Submit') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/employees/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

     <div class="col-md-12 form-group">
        <form method="GET">
            <div class="row form-group">
                <div class="col-md-6">
                    <input type="text" placeholder="Name" class="form-control" name="name" value="<?=isset($_GET["name"]) ? $_GET["name"] : ''?>">
                </div>
            </div>
            <input type="submit" name="search" value="Search" class="btn btn-primary">
            <a href="{{ route('employees.create') }}" class="btn btn-success float-right" role="button" aria-pressed="true">{{ __('Create Employee') }}</a>
        </form>
    </div>


	@if(Session::has('success'))
		<div class="row mb-4 justify-content-center">
			<div class="col-md-12">
	            <div class="alert alert-success" role="alert">
	                {{ Session::get('success') }}
	            </div>
	        </div>
	    </div>
    @elseif(Session::has('error'))
	    <div class="row mb-4 justify-content-center">
			<div class="col-md-12">
	            <div class="alert alert-danger" role="alert">
	                {{ Session::get('error') }}
	            </div>
	        </div>
	    </div>
	@endif

    <div class="row justify-content-left">
        <div class="col-md-12">
            @if('employees')
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Full Name</th>
                            <th scope="col">Practice</th>
                            <th scope="col">Email</th>
                            <th scope="col">Phone</th>
                            <th scope="col">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($employees as $employee)
                            <tr>
                                <td><a href="{{ route('employees.show', $employee) }}">{{ $employee->full_name }}</a></td>
                                <td>@if($employee->practice_id)<a href="{{ route('practices.show', $employee->practice) }}">{{ $employee->practice->name }}</a>@else-@endif</td>
                                <td>@if($employee->email)<a href="mailto:{{ $employee->email }}">{{ $employee->email }}</a>@else-@endif</td>
                                <td>@if($employee->phone)<a href="tel:{{ $employee->phone }}">{{ $employee->phone }}</a>@else-@endif</td>
                                 <td>
                                    <a class="btn btn-sm btn-primary float-left" href="{{ route('employees.edit', $employee) }}">Edit</a>
                                    <form action="{{ route('employees.destroy', $employee) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button onclick="return confirm('Are you sure?')" type="submit" class="btn btn-sm btn-danger" value="Delete">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $employees->links() }}
            @else
            	<p class="alert alert-warning">No employees available. Click <a href="{{ route('employees.create') }}">here</a> to create a new practice.</p>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/employees/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if(Session::has('success'))
        <div class="row mb-4 justify-content-center">
            <div class="col-md-12">
                <div class="alert alert-success" role="alert">
                    {{ Session::get('success') }}
                </div>
            </div>
        </div>
    @elseif(Session::has('error'))
        <div class="row mb-4 justify-content-center">
            <div class="col-md-12">
                <div class="alert alert-danger" role="alert">
                    {{ Session::get('error') }}
                </div>
            </div>
        </div>
    @endif
    
    @if('employee')
     <div class="row md-4 justify-content-left">
        <div class="col-md-5">
            <h2>{{ $employee->full_name }}</h2>
            <hr>
        </div>
    </div>
    <div class="row md-4 justify-content-left">
        <div class="col-md-5">
            <p> First Name: {{ $employee->first_name }} </p>
            <p> Last Name: {{ $employee->last_name }} </p>
            <p> Email: @if($employee->email)<a href="mailto:{{ $employee->email }}">{{ $employee->email }}</a>@else-@endif </p>
            <p> Phone: @if($employee->phone)<a href="tel:{{ $employee->phone }}">{{ $employee->phone }}</a>@else-@endif </p>
            <p> Practice: @if($employee->practice_id)<a href="{{ route('practices.show', $employee->practice) }}">{{ $employee->practice->name}}</a>@else-@endif </p>
        </div>
    </div>
    @endif


    <form id="delete-employee-form" action="{{ route('employees.destroy', $employee) }}" method="POST" style="display: none;">
        @csrf
        @method('DELETE')
    </form>
</div>
@endsection